oocran/django/ns/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url
from .views import (
    state,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/state/$', state, name='state'),
]

oocran/django/oocran/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.views.static import serve
from operators.forms import LoginForm
from operators.views import home

import settings

urlpatterns = [
    url(r'^operators/', include("operators.urls", namespace='operators')),
    url(r'^vnfs/', include("vnfs.urls", namespace='vnfs')),
    url(r'^scripts/', include("scripts.urls", namespace='scripts')),
    url(r'^images/', include("images.urls", namespace='images')),
    url(r'^scenarios/', include("scenarios.urls", namespace='scenarios')),
    url(r'^ns/', include("ns.urls", namespace='ns')),
    url(r'^ues/', include("ues.urls", namespace='ues')),
    url(r'^pools/', include("pools.urls", namespace='pools')),
    url(r'^vims/', include("vims.urls", namespace='vims')),
    url(r'^schedulers/', include("schedulers.urls", namespace='schedulers')),
    url(r'^keys/', include("keys.urls", namespace='keys')),
    url(r'^alerts/', include("alerts.urls", namespace='alerts')),
    url(r'^bbus/', include("bbus.urls", namespace='bbus')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),


    url(r'^login/$', views.login, {'template_name': 'base/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
    url(r'^resources/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

oocran/django/vims/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url

from .views import (
    list,
    create,
    delete,
    details,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/delete/$', delete, name='delete'),
    url(r'^(?P<id>\d+)/$', details, name='details'),
    url(r'^create/$', create, name='create'),
    url(r'^$', list, name="list"),
]

oocran/django/vims/forms.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django import forms


class VimForm(forms.Form):
    name = forms.CharField(max_length=32)
    type = forms.ChoiceField(required=True,widget=forms.Select(attrs={"onChange": 'select(this);'}), choices=[('OpenStack', 'OpenStack'),('AWS','AWS'),('GCE', 'GCE'), ('Azure','Azure')])
    #version = forms.ChoiceField(required=True,widget=forms.Select(attrs={"onChange": 'select(this);'}), choices=[('2', 'Mitaka'),('3','Newton')])

    ip = forms.CharField(max_length=32, initial="controller")
    #sdn_controller = forms.CharField(max_length=32,required = False)
    latitude = forms.FloatField(initial=41.40649)
    longitude = forms.FloatField(initial=2.0787274)
    #OpenStack
    username = forms.CharField(max_length=120,required = False)
    password = forms.CharField(max_length=32, widget=forms.PasswordInput,required = False)
    password_confirmation = forms.CharField(max_length=32, widget=forms.PasswordInput, required = False)
    project_domain = forms.CharField(max_length=120,required = False, initial='default')
    project = forms.CharField(max_length=120,required = False, initial='admin')
    public_network = forms.CharField(max_length=120,required = False, initial='provider')
    domain = forms.CharField(max_length=120,required = False, initial='default')
    #AWS
    access_key_id = forms.CharField(max_length=120,required = False)
    secret_access_key = forms.CharField(max_length=120,required = False)
    session_token = forms.CharField(max_length=120,required = False)
    keypair_name = forms.CharField(max_length=120,required = False)
    #Azure
    tenant_id = forms.CharField(max_length=120,required = False)
    client_id = forms.CharField(max_length=120,required = False)
    client_secret = forms.CharField(max_length=120,required = False)
    subscription_id = forms.CharField(max_length=120,required = False)
    #GCE
    google_project_id = forms.CharField(max_length=120,required = False)
    google_client_email = forms.CharField(max_length=120,required = False)
    google_json_key_location = forms.FileField(required = False)

oocran/django/vims/views.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from .models import Vim, Device, OpenStack, Azure, Aws, Gce
from operators.models import Operator
from images.models import Image
from oocran.global_functions import paginator
from django.contrib.admin.views.decorators import staff_member_required
from .forms import VimForm
from django.contrib.auth.decorators import login_required
from celery import task
from drivers.OpenStack.APIs.keystone.keystone import create_user, delete_user
from drivers.OpenStack.deployments.operator import create_operator


@login_required(login_url='/login/')
def list(request):
    """
    Show list of registered PoP
    :param request:
    :return:
    """
    vims = Vim.objects.all()

    context = {
        "user": request.user,
        "vims": vims,
    }
    return render(request, "vims/list.html", context)


@staff_member_required
def delete(request, id=None):
    """
    Delete PoP with ID id
    :param request:
    :param id:
    :return:
    """
    vim = get_object_or_404(Vim, id=id)
    vim.delete()

    messages.success(request, "VIM successfully deleted!", extra_tags="alert alert-success")
    return redirect("vims:list")


@task()
def add_actual_users(id):
    """
    Register actual operators to the new PoP with ID id
    :param id:
    :return:
    """
    operators = Operator.objects.exclude(name='admin')
    vim = Vim.objects.get(id=id)
    if vim.type == "OpenStack":
        vim = OpenStack.objects.get(name=vim.name)
    for operator in operators:
        create_user(operator, vim)
        create_operator(operator, vim)


@staff_member_required
def create(request):
    """
    Create new PoP
    :param request:
    :return:
    """
    form = VimForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        try:
            Vim.objects.get(name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            if form.cleaned_data['type'] == 'OpenStack':
                if form.cleaned_data['password'] == form.cleaned_data['password_confirmation']:
                    vim = OpenStack.objects.create(name=form.cleaned_data['name'],
                                                    ip=form.cleaned_data['ip'],
                                                    longitude=form.cleaned_data['longitude'],
                                                    latitude=form.cleaned_data['latitude'],
                                                    type=form.cleaned_data['type'],
                                                    password=form.cleaned_data['password'],
                                                    username = form.cleaned_data['username'],
                                                    project_domain = form.cleaned_data['project_domain'],
                                                    project = form.cleaned_data['project'],
                                                    public_network = form.cleaned_data['public_network'],
                                                    domain = form.cleaned_data['domain'],
                                                    )
                    vim.password = vim.encrypt(form.cleaned_data['password'])
                    vim.set_public_network()
                    vim.save()
                else:
                    messages.success(request, "Passwords are different!", extra_tags="alert alert-danger")
            elif form.cleaned_data['type'] == 'AWS':
                vim = Aws.objects.create(name=form.cleaned_data['name'],
                                            ip=form.cleaned_data['ip'],
                                            longitude=form.cleaned_data['longitude'],
                                            latitude=form.cleaned_data['latitude'],
                                            type=form.cleaned_data['type'],
                                            access_key_id=form.cleaned_data['access_key_id'],
                                            secret_access_key = form.cleaned_data['secret_access_key'],
                                            session_token = form.cleaned_data['session_token'],
                                            keypair_name  = form.cleaned_data['keypair_name'],
                                            )
                vim.secret_access_key = vim.encrypt(form.cleaned_data['secret_access_key'])
                vim.save()
            elif form.cleaned_data['type'] == 'Azure':
                vim = Azure.objects.create(name=form.cleaned_data['name'],
                                            ip=form.cleaned_data['ip'],
                                            longitude=form.cleaned_data['longitude'],
                                            latitude=form.cleaned_data['latitude'],
                                            type=form.cleaned_data['type'],
                                            tenant_id = form.cleaned_data['tenant_id'],
                                            client_id = form.cleaned_data['client_id'],
                                            client_secret = form.cleaned_data['client_secret'],
                                            subscription_id = form.cleaned_data['subscription_id'],
                                            )
                vim.client_secret = vim.encrypt(form.cleaned_data['client_secret'])
                vim.save()
            elif form.cleaned_data['type'] == 'GCE':
                vim = Gce.objects.create(name=form.cleaned_data['name'],
                                            ip=form.cleaned_data['ip'],
                                            longitude=form.cleaned_data['longitude'],
                                            latitude=form.cleaned_data['latitude'],
                                            type=form.cleaned_data['type'],
                                            google_project_id=form.cleaned_data['google_project_id'],
                                            google_client_email = form.cleaned_data['google_client_email'],
                                            google_json_key_location = form.cleaned_data['google_json_key_location'],
                                            )
                vim.save()

            add_actual_users.delay(id=vim.id)
            messages.success(request, "VIM successfully register!", extra_tags="alert alert-success")
            return redirect("vims:list")
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("vims:list")

    context = {
        "user": request.user,
        "form": form,
    }
    return render(request, "vims/form.html", context)


@login_required(login_url='/login/')
def details(request, id=None):
    """
    Show details about PoP with ID id
    :param request:
    :param id:
    :return:
    """
    vim = get_object_or_404(Vim, id=id)
    if vim.type == "OpenStack":
        vim = get_object_or_404(OpenStack, name=vim.name)
    elif vim.type == "AWS":
        vim = get_object_or_404(Aws, name=vim.name)
    elif vim.type == "GCE":
        vim = get_object_or_404(Gce, name=vim.name)
    elif vim.type == "Azure":
        vim = get_object_or_404(Azure, name=vim.name)

    context = {
        "user": request.user,
        "vim": vim,
    }
    return render(request, "vims/details.html", context)

oocran/django/vims/templates/vims/details.html
{%extends "base/base.html"%}

{%block content%}
    <h2 class="sub-header">{{vim.name}}</h2>

    <ol class="breadcrumb">
        <li><a href="{% url 'vims:list' %}">VIM</a></li>
        <li class="active">{{vim.name}}</li>
    </ol>

    <h3>Details</h3>
    <div class="panel panel-default" style="float:left;width:47%;margin-right:15px;margin-bottom:50px">
        <div class="panel-heading">Parameters</div>
        <table class="table">
            <tbody>
            <tr>
                <th>Name</th>
                <td>{{vim.name}}</td>
            </tr>
            <tr>
                <th>IP Address</th>
                <td>{{vim.ip}}</td>
            </tr>
            <tr>
                <th>Longitude</th>
                <td>{{vim.longitude}}</td>
            </tr>
            <tr>
                <th>Latitude</th>
                <td>{{vim.latitude}}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{vim.type}}</td>
            </tr>
            </tbody>
        </table>
    </div>

    {% if vim.type == "OpenStack" %}
        {% include "partials/vims/openstack.html" %}
    {% elif vim.type == "GCE" %}
        {% include "partials/vims/gce.html" %}
    {% elif vim.type == "AWS" %}
        {% include "partials/vims/aws.html" %}
    {% elif vim.type == "Azure" %}
        {% include "partials/vims/azure.html" %}
    {% endif %}

    <div id="list" class="tab-pane fade in active">
        <h3>Public IPs</h3>
        <br>
        {% include "partials/vims/ips.html" %}
        <br>

        <a id="submit" href="{% url 'vims:create' %}" class="btn btn-default" role="button" data-toggle="modal" data-target="#myModal">Register</a>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
            </div>
        </div>
    </div>
    
{%endblock content%}

{%block javascript%}{%endblock javascript%}

oocran/django/vims/templates/vims/form.html
{% load staticfiles %}
{% load bootstrap %}


<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">Register VIM</h4>
</div>

<div class="modal-body">
	<form id="form_id" method="POST" action="{% url 'vims:create' %}" enctype="multipart/form-data">
		{%csrf_token%}
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#info">Information</a></li>
			<li><a data-toggle="tab" href="#type">Type</a></li>
		</ul>
		<div class="tab-content">
			<div id="info" class="tab-pane fade in active">
			  	<br>
			  	{{ form.name|bootstrap }}
			  	{{ form.ip|bootstrap }}
                {{ form.latitude|bootstrap }}
                {{ form.longitude|bootstrap }}
			</div>
			<div id="type" class="tab-pane fade">
				<br>
				{{ form.type|bootstrap }}
				<div id="openstack" style="display: block;">
					{{ form.username|bootstrap }}
					{{ form.password|bootstrap }}
					{{ form.password_confirmation|bootstrap }}
					{{ form.project_domain|bootstrap }}
					{{ form.project|bootstrap }}
					{{ form.domain|bootstrap }}
					{{ form.public_network|bootstrap }}
					{{ form.project|bootstrap }}
				</div>
				<div id="aws" style="display: none;">
					{{ form.access_key_id|bootstrap }}
				    {{ form.secret_access_key|bootstrap }}
				    {{ form.session_token|bootstrap }}
				    {{ form.keypair_name|bootstrap }}
			    </div>
			    <div id="azure" style="display: none;">
				    {{ form.tenant_id|bootstrap }}
				    {{ form.client_id|bootstrap }}
				    {{ form.client_secret|bootstrap }}
				    {{ form.subscription_id|bootstrap }}
			    </div>
			    <div id="gce" style="display: none;">
				    {{ form.google_project_id |bootstrap }}
				    {{ form.google_client_email|bootstrap }}
				    {{ form.google_json_key_location|bootstrap }}
			    </div>
			</div>
		</div>
		<input type="submit" class="btn btn-default" value="Register"/>
	</form>
</div>

<script>
	function select(object) {
		if (object.value == "OpenStack") {
			document.getElementById("openstack").style.display = "block";
			document.getElementById("aws").style.display = "none";
			document.getElementById("azure").style.display = "none";
			document.getElementById("gce").style.display = "none";
		}else if (object.value == "AWS") {
			document.getElementById("openstack").style.display = "none";
			document.getElementById("aws").style.display = "block";
			document.getElementById("azure").style.display = "none";
			document.getElementById("gce").style.display = "none";
		}else if (object.value == "Azure") {
		    document.getElementById("openstack").style.display = "none";
			document.getElementById("aws").style.display = "none";
			document.getElementById("azure").style.display = "block";
			document.getElementById("gce").style.display = "none";
		}else if (object.value == "GCE") {
		    document.getElementById("openstack").style.display = "none";
			document.getElementById("aws").style.display = "none";
			document.getElementById("azure").style.display = "none";
			document.getElementById("gce").style.display = "block";
		}else {
			document.getElementById("openstack").style.display = "block";
			document.getElementById("aws").style.display = "none";
			document.getElementById("azure").style.display = "none";
			document.getElementById("gce").style.display = "none";
		}
	}
</script>

oocran/django/vims/templates/vims/list.html
{% extends "base/base.html" %}
{% load staticfiles %}


{% block head %}
   <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyB05V_zAdTZtLZkFTGC17QHXMXs3w6rcSI" async="" defer="defer" type="text/javascript"></script>
   <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
{% endblock head%}

{% block content%}
    <h2 class="sub-header"><i class="fa fa-tasks" aria-hidden="true"></i> Virtual Infrastructure Managers</h2>
    <br>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#list" onclick="list()">List</a></li>
        <li><a data-toggle="tab" href="#localization" onclick="localization()">Localization</a></li>
    </ul>

    <div id="list" class="tab-pane fade in active">
        <br>
        {% include "partials/vims/vims.html" %}
        <br>
        {% if user.is_staff%}
            <a id="submit" href="{% url 'vims:create' %}" class="btn btn-default" role="button" data-toggle="modal" data-target="#myModal">Register</a>

            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content"></div>
                </div>
            </div>
        {%endif%}
    </div>

    <div id="localization" class="tab-pane fade">
        <br>
        <div id="map-canvas" style="width:auto;height:400px;"></div>
    </div>
{% endblock content %}

{%block javascript%}
    <script>
        function list(){
            document.getElementById("localization").style.display = "none";
            document.getElementById("list").style.display = "block";
        }

        function localization(){
            document.getElementById("localization").style.display = "block";
            document.getElementById("list").style.display = "none";
        }
    </script>
    {% include "partials/vims/map.html"%}
{%endblock javascript%}