oocran/django/alerts/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url

from .views import (
    create,
    details,
    delete,
    list,
    listener,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/create/$', create, name='create'),
    url(r'^(?P<id>\d+)/delete/$', delete, name="delete"),
    url(r'^(?P<id>\d+)/$', details, name='details'),
    url(r'^listener/$', listener, name='listener'),
    url(r'^$', list, name="list"),
]

oocran/django/bbus/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url

from .views import (
    details,
    alert,
    scheduler,
    #ue,
    #log,
    #console,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/details/$', details, name='details'),
    url(r'^(?P<id>\d+)/alert/$', alert, name='alert'),
    #url(r'^(?P<id>\d+)/ue/$', ue, name='ue'),
    url(r'^(?P<id>\d+)/scheduler/$', scheduler, name='scheduler'),
    #url(r'^(?P<id>\d+)/log/$', log, name='log'),
    #url(r'^(?P<id>\d+)/console/$', console, name='console'),
    url(r'^$', list, name="list"),
]

oocran/django/ns/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url
from .views import (
    state,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/state/$', state, name='state'),
]

oocran/django/oocran/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.views.static import serve
from operators.forms import LoginForm
from operators.views import home

import settings

urlpatterns = [
    url(r'^operators/', include("operators.urls", namespace='operators')),
    url(r'^vnfs/', include("vnfs.urls", namespace='vnfs')),
    url(r'^scripts/', include("scripts.urls", namespace='scripts')),
    url(r'^images/', include("images.urls", namespace='images')),
    url(r'^scenarios/', include("scenarios.urls", namespace='scenarios')),
    url(r'^ns/', include("ns.urls", namespace='ns')),
    url(r'^ues/', include("ues.urls", namespace='ues')),
    url(r'^pools/', include("pools.urls", namespace='pools')),
    url(r'^vims/', include("vims.urls", namespace='vims')),
    url(r'^schedulers/', include("schedulers.urls", namespace='schedulers')),
    url(r'^keys/', include("keys.urls", namespace='keys')),
    url(r'^alerts/', include("alerts.urls", namespace='alerts')),
    url(r'^bbus/', include("bbus.urls", namespace='bbus')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),


    url(r'^login/$', views.login, {'template_name': 'base/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
    url(r'^resources/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

oocran/django/scenarios/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url

from .views import (
    create,
    details,
    delete,
    list,
    scenario,
    scenarios,
    alert,
    scheduler,
)

urlpatterns = [
    url(r'^create/$', create, name='create'),
    url(r'^(?P<id>\d+)/$', details, name='details'),
    url(r'^(?P<id>\d+)/delete/$', delete, name="delete"),
    url(r'^(?P<id>\d+)/alert/$', alert, name="alert"),
    url(r'^(?P<id>\d+)/scheduler/$', scheduler, name="scheduler"),
    url(r'^(?P<id>\d+)/scenario/$', scenario, name='scenario'),
    url(r'^scenarios/$', scenarios, name="scenarios"),
    url(r'^$', list, name="list"),
]

oocran/django/alerts/views.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.shortcuts import render
from .models import Alert
from operators.models import Operator
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from .forms import AlertForm
from django.contrib.auth.decorators import login_required
from oocran.global_functions import paginator
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json, uuid
from bbus.models import Bbu
from pools.tasks import celery_launch, celery_shut_down


@login_required(login_url='/login/')
def list(request):
    """
    List all the set up alerts
    :param request:
    :return:
    """
    alerts = Alert.objects.filter(operator__user=request.user)
    alerts = paginator(request, alerts)

    context = {
        "user": request.user,
        "alerts": alerts,
    }
    return render(request, "alerts/list.html", context)


@login_required(login_url='/login/')
def details(request, id=None):
    """
    Show details about alert
    :param request:
    :param id: alert ID
    :return:
    """
    alert = get_object_or_404(Alert, id=id)

    context = {
        "user": request.user,
        "alert": alert,
    }
    return render(request, "alerts/details.html", context)


@login_required(login_url='/login/')
def create(request, id=None):
    """
    Create new alert for a VNF
    :param request:
    :param id: VNF ID
    :return:
    """
    bbu = get_object_or_404(Bbu, id=id)
    form = AlertForm(request.POST or None)
    if form.is_valid():
        try:
            Alert.objects.get(operator__user=request.user, name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            alert = form.save(commit=False)
            alert.operator = get_object_or_404(Operator, user=request.user)
            alert.nvf = bbu
            alert.uuid = uuid.uuid4().hex
            alert.save()

            messages.success(request, "Alert created successfully!", extra_tags="alert alert-success")
        return redirect("alerts:list")
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("alerts:list")

    context = {
        "user": request.user,
        "bbu": bbu,
        "form": form,
    }
    return render(request, "alerts/form.html", context)


@login_required(login_url='/login/')
def delete(request, id = None):
    """
    Delete specific alert
    :param request:
    :param id: alert id
    :return:
    """
    alert = get_object_or_404(Alert, id=id)
    alert.delete()

    messages.success(request, "Alert successfully deleted!", extra_tags="alert alert-success")
    return redirect("alerts:list")


@csrf_exempt
def listener(request):
    """
    Trigger the alerts when request comes
    :param request:
    :return:
    """
    for value in request:
        uuid = value.split(',')[0].split(':')[1]
        name = value.split(',')[1].split(':')[1]
        passw = value.split(',')[2].split(':')[1]

        try:
            alert = Alert.objects.get(uuid=uuid, operator__name=name)
            if alert.operator.decrypt() == passw:
                alert.execute()
        except:
            return HttpResponse('pong')

    return HttpResponse('pong')

oocran/django/bbus/views.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from operators.models import Operator
from .forms import AlertForm, SchedulerForm
from .models import Bbu
from ues.models import Ue
from scenarios.models import Scenario
from django.contrib.auth.decorators import login_required
from oocran.global_functions import paginator
from schedulers.models import Scheduler
import uuid
from pools.models import Channel
from alerts.models import Alert
from django.http import HttpResponse
from drivers.OpenStack.APIs.nova.nova import log


@login_required(login_url='/login/')
def details(request, id=None):
    """
    Show the BBU details
    :param request:
    :param id: BBU ID
    :return:
    """
    bbu = get_object_or_404(Bbu, id=id)
    ues = Ue.objects.filter(attached_to=bbu)
    ues = paginator(request, ues)
    alerts = Alert.objects.filter(nvfs=bbu)
    alerts = paginator(request, alerts)
    schedulers = Scheduler.objects.filter(nvfs=bbu)
    schedulers = paginator(request, schedulers)
    try:
        channel = Channel.objects.get(tx=bbu)
    except:
        channel = None

    context = {
        "user": request.user,
        "bbu": bbu,
        "ues": ues,
        "schedulers": schedulers,
        "alerts": alerts,
        "channel": channel
    }
    return render(request, "bbus/details.html", context)


@login_required(login_url='/login/')
def alert(request, id=None):
    """
    Create new alert for the BBU with id ID
    :param request:
    :param id: BBU ID
    :return:
    """
    bbu = get_object_or_404(Bbu, id=id)
    form = AlertForm(request.POST or None)
    if form.is_valid():
        try:
            Alert.objects.get(operator__user=request.user, name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            alert = form.save(commit=False)
            alert.operator = get_object_or_404(Operator, user=request.user)
            alert.uuid = uuid.uuid4().hex
            alert.save()
            alert.nvfs.add(bbu)

            messages.success(request, "Alert created successfully!", extra_tags="alert alert-success")
        return redirect("bbus:details", id=id)
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("bbus:details", id=id)

    context = {
        "user": request.user,
        "bbu": bbu,
        "form": form,
    }
    return render(request, "bbus/alert.html", context)


@login_required(login_url='/login/')
def scheduler(request, id=None):
    """
    Create a new schedule for the BBU with id ID
    :param request:
    :param id: BBU ID
    :return:
    """
    bbu = get_object_or_404(Bbu, id=id)
    form = SchedulerForm(request.POST or None)
    if form.is_valid():
        try:
            Scheduler.objects.get(operator__user=request.user, name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            scheduler = form.save(commit=False)
            scheduler.operator = get_object_or_404(Operator, user=request.user)
            scheduler.save()
            scheduler.nvfs.add(bbu)

            messages.success(request, "Scheduler created successfully!", extra_tags="alert alert-success")
        return redirect("bbus:details", id=id)
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("bbus:details", id=id)

    context = {
        "user": request.user,
        "bbu": bbu,
        "form": form,
    }
    return render(request, "bbus/scheduler.html", context)

oocran/django/schedulers/views.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.shortcuts import render
from .models import Scheduler
from operators.models import Operator
from scenarios.models import Scenario
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from .forms import SchedulerForm
from django.contrib.auth.decorators import login_required
from oocran.global_functions import paginator


@login_required(login_url='/login/')
def list(request):
    schedulers = Scheduler.objects.filter(operator__user=request.user)
    schedulers = paginator(request, schedulers)

    context = {
        "user": request.user,
        "schedulers": schedulers,
    }
    return render(request, "schedulers/list.html", context)


@login_required(login_url='/login/')
def details(request, id=None):
    scheduler = get_object_or_404(Scheduler, id=id)

    context = {
        "user": request.user,
        "scheduler": scheduler,
    }
    return render(request, "schedulers/details.html", context)


@login_required(login_url='/login/')
def create(request, id=None):
    scenario = get_object_or_404(Scenario, id=id)
    form = SchedulerForm(request.POST or None)
    if form.is_valid():
        try:
            Scheduler.objects.get(operator__user=request.user, name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            scheduler = form.save(commit=False)
            scheduler.operator = get_object_or_404(Operator, user=request.user)
            scheduler.scenario = scenario
            scheduler.type = "ns"
            scheduler.save()
            messages.success(request, "Scheduler created successfully!", extra_tags="alert alert-success")
        return redirect("schedulers:list")
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("schedulers:list")

    context = {
        "user": request.user,
        "form": form,
        "scenario": scenario
    }
    return render(request, "schedulers/form.html", context)


@login_required(login_url='/login/')
def delete(request, id=None):
    scheduler = get_object_or_404(Scheduler, id=id)
    scheduler.delete()

    messages.success(request, "Scheduler successfully deleted!", extra_tags="alert alert-success")
    return redirect("schedulers:list")

oocran/django/bbus/templates/bbus/alert.html
{% load bootstrap %}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Alert</h4>
</div>

<div class="modal-body">
	<form method="POST" action="{% url 'bbus:alert' id=bbu.id %}" enctype="multipart/form-data">
        {%csrf_token%}

		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#info">Information</a></li>
            <li><a data-toggle="tab" href="#details">Details</a></li>
		</ul>

		<div class="tab-content">
			<div id="info" class="tab-pane fade in active">
				<br>
				{{form.name|bootstrap}}
				{{form.description|bootstrap}}
			</div>
			<div id="details" class="tab-pane fade">
				<br>
				{{form.action|bootstrap}}
				<div id="script" style="display: none;">
					{{ form.script |bootstrap }}
				</div>
			</div>
		</div>
		<input type="submit" class="btn btn-default" value="Add"/>
	</form>
</div>

<script>
	function select(object) {
		if (object.value == "Reconfigure") {
			document.getElementById("script").style.display = "block";
		} else {
			document.getElementById("script").style.display = "none";
		}
	}
</script>

oocran/django/bbus/templates/bbus/details.html
{%extends "base/base.html"%}
{% load staticfiles %}

{% block head %}
    <script src="{% static 'base/js/jquery.flotgraph.js' %}" xmlns="http://www.w3.org/1999/html"></script>
    <link href="{% static 'base/css/flot.css' %}" rel="stylesheet" type="text/css">
{% endblock head %}

{% block content %}
    <h1>Details of {{bbu.get_name}}</h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'scenarios:scenarios' %}">Scenarios</a></li>
        <li><a href="{% url 'scenarios:scenario' id=bbu.ns.scenario.id %}">{{bbu.ns.scenario}}</a></li>
        <li><a href="{% url 'pools:details' id=bbu.ns.id %}">{{bbu.ns}}</a></li>
        <li class="active">{{bbu.get_name}}</li>
    </ol>

    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#pools">Information</a></li>
        {% if channel != None%}
            <li><a data-toggle="tab" href="#channel">Channel</a></li>
        {% endif %}
        <li><a data-toggle="tab" href="#ues">UEs</a></li>
        <li><a data-toggle="tab" href="#schedulers">Schedulers</a></li>
        <li><a data-toggle="tab" href="#alerts">Alerts</a></li>
    </ul>

    <div class="tab-content">
        <div id="pools" class="tab-pane fade in active">
            <br>
            <div class="panel panel-default" style="float:left;width:48%">
                <div class="panel-heading">Parameters</div>
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>UUID</th>
                            <td>{{bbu.uuid}}</td>
                        </tr>
                        <tr>
                            <th>Power transmistted</th>
                            <td>{{bbu.pt}}</td>
                            <td>dBm</td>
                        </tr>
                        <tr>
                            <th>Central frequency DL</th>
                            <td>{{bbu.freC_DL}}</td>
                            <td>Hz</td>
                        </tr>
                        <tr>
                            <th>Bandwidth DL</th>
                            <td>{{bbu.bw_dl}}</td>
                            <td>Hz</td>
                        </tr>
                        <tr>
                            <th>Central frequency UL</th>
                            <td>{{bbu.freC_UL}}</td>
                            <td>Hz</td>
                        </tr>
                        <tr>
                            <th>Bandwidth UL</th>
                            <td>{{bbu.bw_ul}}</td>
                            <td>Hz</td>
                        </tr>
                        <tr>
                            <th>Simulated</th>
                            <td>{{bbu.is_simulate}}</td>
                            <td></td>
                        </tr>
                        </tbody>
                    </table>
                </div>


            <div class="panel panel-default" style="float:right;width:48%">
                <div class="panel-heading">Resources</div>
                <table class="table">
                    <tbody>
                    <tr>
                        <th>Number of CPUs</th>
                        <td>{{bbu.vnf.cpu}}</td>
                        <td>cores</td>
                    </tr>
                    <tr>
                        <th>RAM</th>
                        <td>{{bbu.vnf.ram}}</td>
                        <td>GB</td>
                    </tr>
                    <tr>
                        <th>Disc Assigned</th>
                        <td>{{bbu.vnf.disc}}</td>
                        <td>GB</td>
                    </tr>
                    <tr>
                        <th>VNF</th>
                        <td><a target="_blank" href="{{bbu.vnf.get_absolut_url}}">{{bbu.vnf}}</a></td>
                        <td></td>
                    </tr>
                    <tr>
                        <th>VIM</th>
                        <td><a target="_blank" href="{{bbu.vim.get_absolut_url}}">{{bbu.vim}}</a></td>
                        <td></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div id="schedulers" class="tab-pane fade">
            <br>
            <h2 class="sub-header">Schedulers</h2>
            {% include "bbus/partials/schedulers.html" %}
            {% include "base/partials/paginator.html" with object_list=schedulers %}
            <br>
            <a href="{% url 'bbus:scheduler' id=bbu.id %}" class="btn btn-default" role="button" data-toggle="modal" data-target="#scheduler">Add</a>

            <div class="modal fade" id="scheduler" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content"></div>
                </div>
            </div>
        </div>

        {% if channel != None %}
            <div id="channel" class="tab-pane fade">
                <br>
                <h2 class="sub-header">Channel</h2>
                <div class="panel panel-default" style="">
                    <div class="panel-heading">Parameters</div>
                    <table class="table">
                        <tbody>
                        <tr>
                            <th>SINR</th>
                            <td>{{channel.sinr}}</td>
                            <td>dBm</td>
                        </tr>
                        <tr>
                            <th>Delay</th>
                            <td>{{channel.delay}}</td>
                            <td>ms</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}

        <div id="ues" class="tab-pane fade">
            <br>
            <h2 class="sub-header">User Equipments</h2>
            {% include "bbus/partials/ues.html" %}
            {% include "base/partials/paginator.html" with object_list=ues %}
        </div>

        <div id="alerts" class="tab-pane fade">
            <br>
            <h2 class="sub-header">Alerts</h2>
            {% include "bbus/partials/alerts.html" %}
            {% include "base/partials/paginator.html" with object_list=alerts %}
            <br>
            <a href="{% url 'bbus:alert' id=bbu.id %}" class="btn btn-default" role="button" data-toggle="modal" data-target="#alert">Add</a>

            <div class="modal fade" id="alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}{% endblock javascript %}

oocran/django/bbus/templates/bbus/form.html
{% load bootstrap %}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">New Pool</h4>
</div>
<div class="modal-body">
    <form method="POST" action="{% url 'utrans:create' id=scenario.id %}" enctype="multipart/form-data">
        {%csrf_token%}
        {{ form|bootstrap }}
        <input type="submit" class="btn btn-default" value="Create"/>
    </form>
</div>

oocran/django/bbus/templates/bbus/scheduler.html
{% load bootstrap %}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Scheduler</h4>
</div>

<div class="modal-body">
	<form method="POST" action="{% url 'bbus:scheduler' id=bbu.id %}" enctype="multipart/form-data">
        {%csrf_token%}
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#information">Information</a></li>
			<li><a data-toggle="tab" href="#action">Action</a></li>
		</ul>
		<div class="tab-content">
			<div id="information" class="tab-pane fade in active">
				<br>
				{{form.name|bootstrap}}
				{{form.description|bootstrap}}
			</div>
			<div id="action" class="tab-pane fade">
				<br>
				{{form.time|bootstrap}}
				{{form.action|bootstrap}}
				<div id="package" style="display: none;">
                    {{form.file|bootstrap}}
                </div>
                <div id="installation" style="display: none;">
                    {{form.script|bootstrap}}
                </div>
				{{form.destroy|bootstrap}}
			</div>
		</div>
		<input type="submit" class="btn btn-default" value="Add"/>
	</form>
</div>

<script>
	function select(object) {
		if (object.value == "Reconfigure") {
			document.getElementById("installation").style.display = "block";
		}else if (object.value == "script") {
		    document.getElementById("package").style.display = "none";
			document.getElementById("installation").style.display = "block";
			$("#Ufile").val('');
		}else if (object.value == "puppet" || object.value == "ansible") {
			document.getElementById("package").style.display = "block";
			document.getElementById("installation").style.display = "none";
			$("#Ufile").val('');
		}else {
			document.getElementById("package").style.display = "none";
			document.getElementById("installation").style.display = "none";
		}
	}
</script>