oocran/django/keys/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url

from .views import (
    create,
    details,
    delete,
    list,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/delete/$', delete, name="delete"),
    url(r'^(?P<id>\d+)/$', details, name='details'),
    url(r'^create/$', create, name='create'),
    url(r'^$', list, name="list"),
]

oocran/django/ns/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url
from .views import (
    state,
)

urlpatterns = [
    url(r'^(?P<id>\d+)/state/$', state, name='state'),
]

oocran/django/oocran/urls.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.views.static import serve
from operators.forms import LoginForm
from operators.views import home

import settings

urlpatterns = [
    url(r'^operators/', include("operators.urls", namespace='operators')),
    url(r'^vnfs/', include("vnfs.urls", namespace='vnfs')),
    url(r'^scripts/', include("scripts.urls", namespace='scripts')),
    url(r'^images/', include("images.urls", namespace='images')),
    url(r'^scenarios/', include("scenarios.urls", namespace='scenarios')),
    url(r'^ns/', include("ns.urls", namespace='ns')),
    url(r'^ues/', include("ues.urls", namespace='ues')),
    url(r'^pools/', include("pools.urls", namespace='pools')),
    url(r'^vims/', include("vims.urls", namespace='vims')),
    url(r'^schedulers/', include("schedulers.urls", namespace='schedulers')),
    url(r'^keys/', include("keys.urls", namespace='keys')),
    url(r'^alerts/', include("alerts.urls", namespace='alerts')),
    url(r'^bbus/', include("bbus.urls", namespace='bbus')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name="home"),


    url(r'^login/$', views.login, {'template_name': 'base/login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/'}, name='logout'),
    url(r'^resources/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

oocran/django/keys/models.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from __future__ import unicode_literals, absolute_import
from django.db import models
from operators.models import Operator
from django.core.urlresolvers import reverse


class Key(models.Model):
    name = models.CharField(max_length=120)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE)
    public_key = models.TextField(null=True, blank=True)
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.name

    def get_absolut_url(self):
        return reverse("keys:details", kwargs={"id": self.id})

    class Meta:
        ordering = ["-timestamp", "-update"]

oocran/django/keys/forms.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django import forms
from .models import Key


class KeyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(KeyForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Key
        fields = [
            "name",
            "public_key",
        ]

oocran/django/keys/views.py
"""
    Open Orchestrator Cloud Radio Access Network

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

from django.shortcuts import render
from .models import Key
from operators.models import Operator
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from .forms import KeyForm
import tasks
from django.contrib.auth.decorators import login_required
from oocran.global_functions import paginator


@login_required(login_url='/login/')
def list(request):
    keys = Key.objects.filter(operator__user=request.user)
    keys = paginator(request, keys)

    context = {
        "user": request.user,
        "keys": keys,
    }
    return render(request, "keys/list.html", context)


@login_required(login_url='/login/')
def details(request, id=None):
    key = get_object_or_404(Key, id=id)

    context = {
        "user": request.user,
        "key": key,
    }
    return render(request, "keys/details.html", context)


@login_required(login_url='/login/')
def create(request, id=None):
    form = KeyForm(request.POST or None)
    if form.is_valid():
        try:
            Key.objects.get(operator__user=request.user, name=form.cleaned_data['name'])
            messages.success(request, "Name repeated!", extra_tags="alert alert-danger")
        except:
            key = form.save(commit=False)
            key.operator = get_object_or_404(Operator, user=request.user)
            key.save()
            #tasks.add.delay(key.id)
            messages.success(request, "Key created successfully!", extra_tags="alert alert-success")
        return redirect("keys:list")
    if form.errors:
        messages.success(request, form.errors, extra_tags="alert alert-danger")
        return redirect("keys:list")

    context = {
        "user": request.user,
        "form": form,
    }
    return render(request, "keys/form.html", context)


@login_required(login_url='/login/')
def delete(request, id=None):
    key = get_object_or_404(Key, id=id)
    #tasks.delete.delay(key.id)
    key.delete()

    messages.success(request, "Key successfully deleted!", extra_tags="alert alert-success")
    return redirect("keys:list")

oocran/django/keys/templates/keys/details.html
{%extends "base/base.html"%}

{% block head %}
   <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
{% endblock head%}

{%block content%}
	<h1>Details of {{scheduler.name}}</h1>
    <h3>Time: {{scheduler.time|time:"H:i"}}</h3>
    <br/>
    <h3>Description</h3>
    <div class="panel panel-default">
        <div class="panel-body">
            {{scheduler.description | linebreaksbr}}<br/>
        </div>
    </div>
    <h3>Nvfs</h3>
    <div class="panel panel-default">
        <div class="panel-body">
            {% for nvf in scheduler.nvfs.all %}
                <a href="{{nvf.get_absolut_url}}">{{nvf.name}}</a><br>
            {% endfor %}
        </div>
    </div>
    <h3>Script</h3>
    <div class="panel panel-default">
        <div class="panel-body">
            {{scheduler.script | linebreaksbr}}<br/>
        </div>
    </div>
    <h3>File</h3>
    <div class="panel panel-default">
        <div class="panel-body">

        </div>
    </div>
{%endblock content%}

{%block javascript %}{%endblock javascript %}

oocran/django/keys/templates/keys/form.html
{% load bootstrap %}

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	<h4 class="modal-title" id="myModalLabel">New Scheduler</h4>
</div>

<div class="modal-body">
	<form method="POST" action="{% url 'keys:create' %}" enctype="multipart/form-data">
        {%csrf_token%}
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#info">Information</a></li>
		</ul>
		<div class="tab-content">
			<div id="info" class="tab-pane fade in active">
				<br>
				{{form.name|bootstrap}}
				{{form.public_key|bootstrap}}
			</div>
		</div>
		<input type="submit" class="btn btn-default" value="Add"/>
	</form>
</div>

oocran/django/keys/templates/keys/list.html
{% extends "base/base.html" %}

{% block content%}
	<h2 class="sub-header"><i class="fa fa-key" aria-hidden="true"></i> Keys</h2>
    {% include "partials/keys.html" %}
    {% include "base/partials/paginator.html" with object_list=keys %}
    <br>
    <a id="submit" href="{% url 'keys:create' %}" class="btn btn-default" role="button" data-toggle="modal" data-target="#myModal">Create</a>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content"></div>
        </div>
    </div>
{% endblock content %}

{% block javascript %}{% endblock javascript %}